##### Cancer Genome Interpreter ######
cancerGenes_url: 'https://www.cancergenomeinterpreter.org/data/catalog_of_cancer_genes_latest.zip'
cancerVariants_url: 'https://www.cancergenomeinterpreter.org/data/catalog_of_validated_oncogenic_mutations_latest.zip'
cancerBioactivities_url: 'https://www.cancergenomeinterpreter.org/data/cancer_bioactivities_latest.zip'

cancerBiomarkers_url: 'https://www.cancergenomeinterpreter.org/data/cgi_biomarkers_latest.zip'
cancerBiomarkers_variant_file: 'cgi_biomarkers_per_variant.tsv'

amino_acids: 
    'A': 'Ala'
    'C': 'Cys'
    'D': 'Asp'
    'E': 'Glu'
    'F': 'Phe'
    'G': 'Gly'
    'H': 'His'
    'I': 'Ile'
    'K': 'Lys'
    'L': 'Leu'
    'M': 'Met'
    'N': 'Asn'
    'P': 'Pro'
    'Q': 'Gln'
    'R': 'Arg'
    'S': 'Ser'
    'T': 'Thr'
    'V': 'Val'
    'W': 'Trp'
    'Y': 'Tyr'

entities_header: 
    - 'ID'
    - ':LABEL'
    - 'alternative_names'
    - 'chromosome'
    - 'position'
    - 'reference'
    - 'alternative'
    - 'effect'
    - 'oncogeneicity'
    - 'source'
relationships_headers:
    'targets_clinically_relevant_variant':
        - 'START_ID'
        - 'END_ID'
        - 'TYPE'
        - 'evidence'
        - 'response'
        - 'disease'
        - 'type'
        - 'source'
    'targets':
        - 'START_ID'
        - 'END_ID'
        - 'TYPE'
        - 'evidence'
        - 'response'
        - 'disease'
        - 'type'
        - 'source'
    'associated_with':
        - 'START_ID'
        - 'END_ID'
        - 'TYPE'
        - 'score'
        - 'evidence_type'
        - 'source'
        - 'number_publications'
    'known_variant_is_clinically_relevant':
        - 'START_ID'
        - 'END_ID'
        - 'TYPE'
        - 'source'

