###### Exposome Explorer Database ########
database_urls: 
    - 'http://exposome-explorer.iarc.fr/system/downloads/current/biomarkers.csv.zip'
    - 'http://exposome-explorer.iarc.fr/system/downloads/current/correlations.csv.zip'

relationships_header: 
    'food':
        - 'START_ID'
        - 'END_ID'
        - 'TYPE'
        - 'intake_median'
        - 'intake_units'
        - 'biosample'
        - 'method'
        - 'corr'
        - 'ci_low'
        - 'ci_high'
        - 'pvalue'
        - 'significant'
        - 'publication'
        - 'source'


