#### GWAS Catalog #####
GWASCat_url: 'https://www.ebi.ac.uk/gwas/api/search/downloads/alternative'
entities_header: 
    - 'ID'
    - 'TYPE'
    - 'title'
    - 'date'
    - 'sample_size'
    - 'replication_size'
    - 'trait'
relationships_header:
    published_in_publication: 
        - 'START_ID'
        - 'END_ID'
        - 'TYPE'
        - 'source'
    variant_found_in_gwas:
        - START_ID
        - END_ID 
        - TYPE
        - frequency
        - pvalue
        - odds_ratio
        - trait
        - source
    studies_trait:
        - START_ID
        - END_ID 
        - TYPE
        - source
