##### HUGO Gene Nomenclature #######
hgnc_url: 'ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt'
header: 
    - 'ID'
    - ':LABEL'
    - 'name'
    - 'family'
    - 'synonyms'
    - 'taxid'
