##### Human Metabolome Database #######
HMDB_url: 'http://www.hmdb.ca/system/downloads/current/hmdb_metabolites.zip'
HMDB_DO_source: 'OMIM'
HMDB_dictionary_file: 'mapping.tsv'
relationships_header: 
    - 'START_ID'
    - 'END_ID'
    - 'TYPE'
    - 'source'
HMDB_fields: 
    - 'accession'
    - 'name'
    - 'description'
    - 'chemical_formula'
    - 'average_molecular_weight'
    - 'monoisotopic_molecular_weight'
    - 'status'
    - 'origin'
    - 'drugbank_id'
    - 'foodb_id'
    - 'knapsack_id'
    - 'chemspider_id'
    - 'biocyc_id'
    - 'bigg_id'
    - 'wikipedia'
    - 'mugowiki'
    - 'mutagene'
    - 'metlin_id'
    - 'pubchem_compound_id'
    - 'het_id'
    - 'chebi_id'
    - 'tissue'
    - 'cellular_location'

HMDB_parentFields: 
    - 'synonyms'
    - 'origins'
    - 'taxonomy'
    - 'cellular_locations'
    - 'biofluid_locations'
    - 'tissue_locations'
    - 'pathways'
    - 'diseases'
    - 'general_references'
    - 'protein_associations'

HMDB_structures: 
    'pathways': 
        - 'smpdb_id'
    'diseases':
        - 'omim_id'
    'synonyms':
        - 'synonym'
    'protein_associations':
        - 'uniprot_id'
    'cellular_locations':
        - 'cellular_location'
    'biofluid_locations':
        - 'biofluid'
    'general_references':
        - 'pubmed_id'
    'taxonomy':
        - 'direct_parent'
        - 'kingdom'
        - 'super_class'
        - 'class'
        - 'sub_class'

HMDB_associations: 
    'pathways': 
        - 'ANNOTATED_IN_PATHWAY'
        - 'hmdb_annotated_in_pathway'
    'diseases': 
        - 'ASSOCIATED_WITH'
        - 'hmdb_associated_with_disease'
    'protein_associations': 
        - 'ASSOCIATED_WITH'
        - 'hmdb_associated_with_protein'
    'cellular_locations': 
        - 'ASSOCIATED_WITH'
        - 'hmdb_associated_with_cellular_location'
    'biofluid_locations': 
        - 'ASSOCIATED_WITH'
        - 'hmdb_associated_with_biofluid_location'
    'general_references': 
        - 'MENTIONED_IN_PUBLICATION'
        - 'Metabolite_Publication_mentioned_in_publication'
    'tissue_locations':
        - 'ASSOCIATED_WITH'
        - 'hmdb_associated_with_tissue'
    
HMDB_attributes: 
    - 'name'
    - 'description'
    - 'direct_parent'
    - 'kingdom'
    - 'super_class'
    - 'class'
    - 'sub_class'
    - 'chemical_formula'
    - 'average_molecular_weight'
    - 'monoisotopic_molecular_weight'
    - 'pubchem_compound_id'
    - 'foodb_id'
    - 'status'
    - 'knapsack_id'
    - 'chemspider_id'
    - 'biocyc_id'
    - 'bigg_id'
    - 'wikipedia'
    - 'mugowiki'
    - 'mutagene'
    - 'metlin_id'
    - 'het_id'
    - 'chebi_id'
    - 'synonyms'
