###### IntAct Database #######
intact_psimitab_url: 'ftp://ftp.ebi.ac.uk/pub/databases/intact/current/psimitab/intact.txt'
header: 
    - 'START_ID'
    - 'END_ID'
    - 'TYPE'
    - 'score'
    - 'interaction_type'
    - 'method'
    - 'source'
    - 'publications'
