###### PathwayCommons Database #######
pathwayCommons_pathways_url: 'http://www.pathwaycommons.org/archives/PC2/v9/PathwayCommons9.All.uniprot.gmt.gz'

pathway_type: -45

pathways_header: 
    - ID
    - ':LABEL'
    - name
    - description
    - organism
    - source
    - linkout

relationships_header: 
    - START_ID
    - END_ID
    - TYPE
    - linkout
    - source
